# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jOkmmacGyY004nnrihkNJHq6mdlY1YEq
"""

import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

classifier =Sequential()

classifier.add(Dense(units=100, activation='relu', input_dim=11))

classifier.add(Dense(units=50, activation='relu'))

classifier.add(Dense(units=1, activation='sigmoid'))

classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model_history = classifier.fit(x_train, y_train, batch_size=100, validation_split=0.2, epochs=100)

